import jc.st.el.CustomContext;
import jc.st.el.CustomExpressionFactoryImpl;

import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Person person = new Person();
        person.id = "xjfljskljdfklsjaf";
        person.setName("test");
        person.address.id = "1002021";
        person.address.city = "Shanghai";
        person.address.country = "China";

        ExpressionFactory factory = new CustomExpressionFactoryImpl();
        CustomContext context = new CustomContext(person);
        ValueExpression valueExpression = factory.createValueExpression(context, "{{address.city}} is my home", Person.class);
        System.out.println(valueExpression.getValue(context));

//        String s = "Hey,{{perso{n.name}}, {{person.address.city} is my home";
//        try {
//            new Parser(s).Build();
//        } catch (Exception ex) {
//            System.out.println(ex.getMessage());
//        }
//        s="{{person.name}}, {{person.address.city}}";
//        new Parser(s).Build();
//        s="hi{{person.name}}";
//        new Parser(s).Build();
//        s="this is a test";
//        new Parser(s).Build();
//        s="this is a test {{}}";
//        new Parser(s).Build();

    }

    public static class Person {
        public Person() {
            this.address = new Address();
        }

        public String id;
        private String name;
        public Address address;

        public Address getAddress() {
            return this.address;
        }

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public class Address {
            public String id;
            public String country;
            public String city;

            public String getCity() {
                return this.city;
            }
        }
    }
}
